# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ingredient')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
        ),
        migrations.CreateModel(
            name='salesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
        ),
        migrations.CreateModel(
            name='salesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totolPrice', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.member')),
            ],
        ),
        migrations.CreateModel(
            name='stockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('ingredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.supplier'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='storeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.store'),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='salesRecordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.salesRecord'),
        ),
    ]
